### ISSUE TITLE
help_wanted

### ISSUE THREAD

**Issue by borja-alvarez** [UDC-FIC-VVS/sistema-de-correo-electronico-borjaja#3]
En el commit [804f856](https://github.com/UDC-FIC-VVS/sistema-de-correo-electronico-borjaja/commit/804f856a1f7a7e388d916ff896f0eff092bf9c8b)

Estaba intentando hacer un test para la parte indicada a continuación en los requisitos:

**Un correo electrónico (Mensaje) debe ser un arquivo de texto plano (Texto)** cunha marca de lectura, marca que debe ser editable (debe poderse marcar un correo electrónico como lido ou non lido segundo se queira). Os correos electrónicos poderán organizarse en carpetas, que á súa vez poderán estar contidas noutras carpetas.

Sin embargo en la clase Mensaje.java no hay ningún metodo que me devuelva La clase Texto por lo que no puedo comprobar que el tipo de esta clase sea el MimeType "text/plain" para validar que sea un texto.

**Comment by lauramcastro** [comment]
Certamente, ese atributo é privado e non ten un _get_ "puro", senón que a información que contén (almacenada polo obxecto Texto) é accesible de xeito indirecto a través do método _obtenerVisualización()_.

Non sei se con isto che resolvo a dúbida, se é así podes pechar a issue. E desculpa a demora en responderche!
