### ISSUE TITLE
Help_wanted Log

### ISSUE THREAD

**Issue by borja-alvarez** [UDC-FIC-VVS/sistema-de-correo-electronico-borjaja#7]
Hola @lauramcastro ,

Acabo de realizar el test sobre el fichero Log, ahora mismo solo hay un método que hace logs pero en los requisitos pone "Debe implementarse a posibilidade de que os servizos de arquivado inclúan un servizo de log que rexistre por saída estándar información sobre **as peticións recibidas**". ¿Tengo que hacer test aunque el resto de métodos no estén desarrollados?

**Comment by lauramcastro** [comment]
Ola, Borja: vós non tedes que realizar ningún desenvolvemento.

O requisito que indicas cúmplese precisamente co deseño e implementación desa subclase Log: cando se quere ("posibilidade") que algún servizo de arquivado faga _log_ das peticións de almacenamento, entón hai que decorar o arquivador cun obxecto Log. É dicir, a especificación está implementada (confío ter entendido e resolto a túa dúbida).
